export const DynamicAsideMenuConfig = {
  items: [
    { section: 'MENU.ADMIN_DASHBOARD' },
    {
      id: "dashboard",
      title: 'Dashboard',
      root: true,
      icon: 'fab fa-dashcube',
      svg: './assets/media/svg/icons/Design/Layers.svg',
      page: '/dashboard',
      translate: 'MENU.DASHBOARD',
      bullet: 'dot',
      isActive: false
    },
    {
      id: "category-group",
      title: 'category',
      root: true,
      icon: 'fas fa-grip-horizontal',
      svg: './assets/media/svg/icons/Design/Layers.svg',
      translate: 'Categories',
      page: '/category',
      bullet: 'dot',
      isActive: false,
    },
    {
      id: "items-list-group",
      title: 'items-for-sale',
      root: true,
      icon: 'fas fa-shopping-cart',
      svg: './assets/media/svg/icons/Design/Layers.svg',
      translate: 'Products',
      bullet: 'dot',
      isActive: false,
      page: '/items-for-sale',
    },
    {
      id: "units",
      title: 'units',
      root: true,
      icon: 'fas fa-network-wired',
      svg: './assets/media/svg/icons/Design/Layers.svg',
      translate: 'Units',
      bullet: 'dot',
      isActive: false,
      page: '/units',
    },
    {
      id: "site-content",
      title: 'site-content',
      root: true,
      icon: 'fab fa-dashcube',
      svg: './assets/media/svg/icons/Design/Layers.svg',
      page: '/about-us',
      translate: 'Site Content',
      bullet: 'dot',
      isActive: false
    },
    // {
    //   id: "orders",
    //   title: 'orders',
    //   root: true,
    //   icon: 'fas fa-file-invoice-dollar',
    //   svg: './assets/media/svg/icons/Design/Layers.svg',
    //   page: '/orders',
    //   translate: 'Orders',
    //   bullet: 'dot',
    //   isActive: false,
    // },
  ]
};
